apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
    name: use-pvspec-dan
spec:
  containers:
  - image: nginx
    name: use-pv
    volumeMounts:
    - name: nginx-persistent-storage
      mountPath: /data
  volumes:
  - name: pv-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
