apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging-service
    tier: msg
  name: messaging-service
  namespace: default
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
